#!/bin/sh
# Copies env-specific Firebase plist and wires non-prod Google Sign-In iOS client (558349).
# Invoked by Runner target build phase "Copy GoogleService-Info".
# Do not run manually unless debugging; flutter run --flavor {env} triggers this.
set -euo pipefail

SRCROOT="${SRCROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
REPO_ROOT="$(cd "${SRCROOT}/.." && pwd)"
CONFIG="${CONFIGURATION:-Debug}"

case "$CONFIG" in
  *-local) ENV=local ;;
  *-dev)   ENV=dev ;;
  *-stg)   ENV=stg ;;
  *-prd)   ENV=prd ;;
  *)
    echo "warning: CONFIGURATION='${CONFIG}' has no -local|-dev|-stg|-prd suffix; defaulting to dev" >&2
    ENV=dev
    ;;
esac

SRC="${SRCROOT}/Runner/Firebase/GoogleService-Info.${ENV}.plist"
DST="${SRCROOT}/Runner/GoogleService-Info.plist"
SIGNIN_SRC="${SRCROOT}/Runner/Firebase/GoogleSignIn.${ENV}.plist"
GENERATED_DART="${REPO_ROOT}/lib/config/generated_google_signin_client.dart"

write_generated_dart_null() {
  {
    printf '%s\n' "// Generated by ios/scripts/copy_google_service_info.sh — do not edit."
    printf '%s\n' "$1"
    printf '%s\n' "const String? kGoogleSignInIosClientId = null;"
  } > "$GENERATED_DART"
}

write_generated_dart_client() {
  {
    printf '%s\n' "// Generated by ios/scripts/copy_google_service_info.sh — do not edit."
    printf '%s\n' "// Source: ios/Runner/Firebase/GoogleSignIn.${ENV}.plist"
    printf '%s\n' "const String? kGoogleSignInIosClientId = '${1}';"
  } > "$GENERATED_DART"
}

if [ ! -f "$SRC" ]; then
  echo "error: missing Firebase plist for env='${ENV}': ${SRC}" >&2
  echo "error: add the file under Runner/Firebase/ (stg is intentionally unset until provisioned)." >&2
  exit 1
fi

cp "$SRC" "$DST"
echo "Copied GoogleService-Info.${ENV}.plist → Runner/GoogleService-Info.plist (CONFIGURATION=${CONFIG})"

if command -v plutil >/dev/null 2>&1; then
  SERVER_CLIENT_ID="$(plutil -extract SERVER_CLIENT_ID raw -o - "$DST" 2>/dev/null || true)"
  if [ -n "$SERVER_CLIENT_ID" ]; then
    echo "GoogleService-Info SERVER_CLIENT_ID (${ENV}): ${SERVER_CLIENT_ID}"
  else
    echo "warning: SERVER_CLIENT_ID missing in ${DST}" >&2
  fi
fi

SIGNIN_CLIENT_ID=""
if [ -f "$SIGNIN_SRC" ] && command -v plutil >/dev/null 2>&1; then
  SIGNIN_CLIENT_ID="$(plutil -extract CLIENT_ID raw -o - "$SIGNIN_SRC" 2>/dev/null || true)"
fi

if [ "$ENV" = "local" ] || [ "$ENV" = "dev" ]; then
  if [ -n "$SIGNIN_CLIENT_ID" ]; then
    write_generated_dart_client "$SIGNIN_CLIENT_ID"
    echo "GoogleSignIn iOS CLIENT_ID (${ENV}): ${SIGNIN_CLIENT_ID}"
    reversed="com.googleusercontent.apps.${SIGNIN_CLIENT_ID%.apps.googleusercontent.com}"
    if ! /usr/libexec/PlistBuddy -c "Print :CFBundleURLTypes:0:CFBundleURLSchemes" \
        "${SRCROOT}/Runner/Info.plist" 2>/dev/null | rg -F "$reversed" >/dev/null; then
      echo "warning: Info.plist missing URL scheme for 558349 Sign-In: ${reversed}" >&2
      echo "warning: run: /bin/sh ios/scripts/register_google_signin_url_schemes.sh" >&2
    fi
  else
    write_generated_dart_null "// Fill ios/Runner/Firebase/GoogleSignIn.{local,dev}.plist CLIENT_ID (GCP 558349443875 iOS OAuth)."
    echo "warning: GoogleSignIn.${ENV}.plist CLIENT_ID empty — iOS idToken may fail (558349 iOS OAuth needed)." >&2
    echo "warning: GCP Console → project 558349443875 → Credentials → iOS OAuth for Bundle ID in plist." >&2
  fi
elif [ "$ENV" = "prd" ]; then
  write_generated_dart_null "// prd uses Firebase plist CLIENT_ID (841694)."
fi
