// Generated by ios/scripts/copy_google_service_info.sh — do not edit.
// Source: ios/Runner/Firebase/GoogleSignIn.dev.plist
const String? kGoogleSignInIosClientId = '558349443875-7quvithfufd1ps0i426vb56sut9s9ku9.apps.googleusercontent.com';
